name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    steps:
      - uses: actions/checkout@v2 
      - run: python3 cpplint.py --extensions=cpp modules/*
      - run: cppcheck --error-exitcode=1 --enable=all --suppress=missingIncludeSystem modules/
  build:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: cmake .
    - name: Upload tests
      uses: actions/upload-artifact@v2
      with:
        path: tests
  test:
    runs-on: ubuntu-latest
    container: keberson/vk-gcc
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: cmake . &&  cmake --build . &&  CTEST_OUTPUT_ON_FAILURE=TRUE cmake --build . --target test
